# This file defines the entire conda environment for the YOLO ECG project.
# To create the environment, run: conda env create -f environment.yml
# To update the environment, run: conda env update -f environment.yml

name: yolo_env

channels:
  - pytorch   # Channel for official PyTorch builds
  - nvidia    # Channel for CUDA toolkit
  - defaults  # The default conda channel

dependencies:
  # --- Core Conda Packages ---
  # Specify the Python version
  - python=3.9

  # Specify PyTorch, torchvision, and the CUDA toolkit version.
  # Conda will install the correct, compatible binaries for your system.
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # Or 12.1, etc. Match your GPU driver capability.

  # Other core libraries managed by conda for best binary compatibility
  - numpy
  - matplotlib
  - opencv  # The conda package for opencv-python is just 'opencv'

  # --- Pip-only Packages ---
  # Conda will first install the packages above, then use pip
  # to install any packages listed here.
  - pip
  - pip:
    - ultralytics