name: yolo_env

channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  # Packages
  - python=3.9


  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - matplotlib
  - opencv
  - pip
  - pip:
    - ultralytics