paper_len: 10.0
abs_lead_step: 10
tickLength: 8 
tickSize_step: 0.002 
rhythm_strip_len_seconds: 10.0
dc_offset_length: 0.2
columns: 4 # number of columns for the main lead display
# The precise order of leads for the visual layout
desired_order: 
  - I
  - aVR
  - V1
  - V4
  - II
  - aVL
  - V2
  - V5
  - III
  - aVF
  - V3
  - V6

# ECG PAPER LAYOUT PARAMETERS
layout_parameters:
  # Paper dimensions in inches (standard US Letter)
  width: 11.0
  height: 8.5

  # Grid spacing in mV (vertical) and seconds (horizontal)
  y_grid_size: 0.5
  x_grid_size: 0.2

  # Physical size of a major grid box in inches (standard is 5mm)
  # The value is 5 / 25.4, pre-calculated
  y_grid_inch: 0.19685 
  x_grid_inch: 0.19685
  
  # Line widths for plotting
  grid_line_width: 0.5
  line_width: 0.75

  # Font and text properties
  lead_fontsize: 11

  # Spacing and layout properties
  x_gap: 1.0
  row_height: 8.0
  dc_offset_length: 0.2 # Length of the calibration pulse in seconds

  # Bounding box calculation parameters
  min_bbox_height_mv: 2.0
  bbox_vertical_margin_mv: 0.1

# COLORS
colors:
  standard_sets:
    colour5:
      major: [1, 0, 0] # Red
      minor: [0.996, 0.8745, 0.8588] # Light Pinkish